### PR TITLE
Edit dataset

### LINKED ISSUE #686: Data Page design: users can create, name, edit, and share queries over the data in the metadata catalogue
Queries: data sets.
Metadata catalogue: combination of data records, data objects, and tags on both.

Preliminary ideas:

Consider tagging the queries such that UI could display collections of the queries providing a thematic view over the metadata.

The collections of the metadata queries can be curated by group owners.

### LINKED ISSUE #687: Data Page: add map for data selection using polygons

### LINKED ISSUE #711: As User, on Data records tab of Data page, I can select individual data-records and request processing
Deployment receives the list of the selected assets.

### LINKED ISSUE #712: As User, on Data records tab of Data page, I can capture the used query and create Data set out of it
By default, include the time window in the filter as well, but allow to opt-out.

### LINKED ISSUE #713: Grey out top menu +Add button when on Data record tab of Data page
This is a bug report against current implementation in https://github.com/nuvla/ui/tree/edit-dataset branch.

### LINKED ISSUE #714: As User, I can use map on the Data page to select an area where to search for the data-record assets
Initial implementation 
 * take the current view of the map as the bounding box

Example. The view below zoomed in on an island. Take the full bounding box and provide it to the filter.

Screenshot 2021-11-15 at 10 57 40

This implementation would correspond to this data browser https://browser.creodias.eu/

### LINKED ISSUE #718: As User, when defining a data set, I can consult all current apps that can work with the data set
See #717 for renaming "Module filter" to Applications.

### LINKED ISSUE #731: allow owner to delete data sets via Data page

### LINKED ISSUE #742: on Data records tab of Data page, allow user to create a data set out of the selected data records
On the screenshot, three data records are selected. Add a possibility to turn them into a data set.

Screenshot 2021-12-02 at 10 17 35

### LINKED ISSUE #745: allow to collapse maps on each view in the Data page
For PR #732

### LINKED ISSUE #748: when on Map and showing pre-selected records, zoom out to the bounding box containing the full selection of the records

### LINKED ISSUE #752: on Data-record page of Data, add selection of records on map and persists the WKT query with data-set if requested

### LINKED ISSUE #753: Multiple world issue, elements visible on one map are not on others, limit to one world

### LINKED ISSUE #756: When no data-records to show show a message No data-records

### PR DESCRIPTION
**Pull request by 0xbase12**
WIP do not merge

Resolves #752, resolves #753, resolves #756, resolves #745, resolves #748, resolves #686, resolves #687, resolves #711, resolves #712, resolves #713, resolves #714, resolves #718, resolves #731, resolves #742

### CODE REVIEW

**Comment by konstan** [comment]
@0xbase12 

The table view is skewed for some reason

Screenshot 2021-11-24 at 11 25 03

**Comment by konstan** [comment]
@0xbase12 Where should I see the delete button? (https://github.com/nuvla/ui/issues/731)

Screenshot 2021-11-24 at 14 55 26

**Comment by 0xbase12** [comment]
When you have the right to delete a data-set, a delete button will be visible in the menu bar

**Comment by konstan** [comment]
I can see it now. Thanks.

**Comment by konstan** [comment]
@0xbase12 I see ID mismatch on the data set page

Screenshot 2021-11-24 at 15 26 24

**Comment by konstan** [comment]
**process** button is active, but no data set selected.

Screenshot 2021-11-24 at 15 29 58

**Comment by konstan** [comment]
**Process** button is not "greyed out" on the data records page (where no selection of the assets is possible). Also, the button does nothing.


Screenshot 2021-11-24 at 15 32 43

**Comment by konstan** [comment]
... unless it's in WIP.

**Comment by 0xbase12** [comment]
> **Process** button is not "greyed out" on the data records page (where no selection of the assets is possible). Also, the button does nothing.
> 
> Screenshot 2021-11-24 at 15 32 43

What about removing all left buttons in data-record page, since it's only for data-set list page ?

**Comment by 0xbase12** [comment]
> **process** button is active, but no data set selected.
> 
> Screenshot 2021-11-24 at 15 29 58

How happened this situation, did you deleted a selected data-set?

**Comment by konstan** [comment]
> What about removing all left buttons in data-record page, since it's only for data-set list page ?

I would definitely remove Add. 
However, data-records can be selected for processing - see https://github.com/nuvla/ui/issues/711. So, **Process** button should behave the same as on the data set page.

**Comment by konstan** [comment]
> How happened this situation, did you deleted a selected data-set?

I think I edited it (added tags and updated filter), which might have created a new data set :/ Also, as nuvla-admin I can see two data sets

Screenshot 2021-11-24 at 15 58 51

but not as the user that was working on them

Screenshot 2021-11-24 at 15 59 29

**Comment by konstan** [comment]
> Also, as nuvla-admin I can see two data sets ...
> but not as the user that was working on them

I'm the owner of both of them. But I can only see them when I'm in navsci group (with which both data sets are shared).

I also added https://github.com/nuvla/ui/issues/735

**Comment by 0xbase12** [comment]
Bug in data-set process. In case user select data-sets in different pages, not all of them will be processed.

**Comment by konstan** [comment]
@0xbase12 Just got this when starting App. Any idea why?

image (6)

**Comment by konstan** [comment]
@0xbase12 That screenshot is from another user. I tried myself, several times - I can't reproduce this. Please don't spend time on that.

**Comment by konstan** [comment]
@0xbase12 clicking on `Map Filter` and `Data records` page 
Screenshot 2021-12-20 at 14 42 37

renders blank page
Screenshot 2021-12-20 at 14 42 43

**Pull request merged**
