### PR TITLE
Progress bars

### PR DESCRIPTION
**Pull request by mebster**
Addresses #558

### CODE REVIEW

**Comment by 0xbase12** [comment]
Screenshot 2021-03-26 at 14 46 39
Why the progress bar is under some tabs but not others like vulnerabilities. Isn't it easier to put it like the job warning message and it will be everywhere without having to insert it in every tab?

**Comment by 0xbase12** [comment]
Found two bug related to dashboard deployment page changes push fixes directly to your pull-request

**Comment by mebster** [comment]
Yes we could put the bars above the tabs.  Initially I didn't like the idea, but why not.  It's true that it makes sense to have them at the same level as the messages.  Btw, we'll have to add a bit more logic not to always show error messages, especially when other successful actions have occurred since.

**Comment by mebster** [comment]
And thanks for the fixes 👍

**Pull request merged**
