### PR TITLE
add radar plot

### LINKED ISSUE #289: add radar plot, grouped by `platform` and `state`

### PR DESCRIPTION
**Pull request by cjdcordeiro**
fixes #289

### CODE REVIEW

**Comment by 0xbase12** [comment]
- I'm not able to see values in the radar
Screenshot 2019-12-12 at 09 38 27
- I think that we should display pie and radar side by side to not take all that space
- For the aggregation, we should be coherent in what we want to display. By that I mean. You want to show stats for displayed values in the table only or for all of them?
- If we use cimi aggregation, it's for all of them independently of the paggination (first, last)
- Please merge master into your branch
- Fix format indentation to 2 space and align binding into maps

**Comment by cjdcordeiro** [comment]
from your 8 vouchers, how many are new? if they are all the same state, then all you'll see is a line, from the center of the web to the NEW vertex 

> I think that we should display pie and radar side by side to not take all that space

yes. I wasn't able to do that.

> For the aggregation, we should be coherent in what we want to display. By that I mean. You want to show stats for displayed values in the table only or for all of them?

every plot appearing below the search menu, only consider the `subs/collection` results...there are no plots yet for "all of them"

> If we use cimi aggregation, it's for all of them independently of the paggination (first, last)

yes. I think that's how it should be and that's what `subs/collection` returns I believe. That's how it's implemented

**Comment by cjdcordeiro** [comment]
@0xbase12 all fixed

**Comment by 0xbase12** [comment]
The radar plot is not visible on mobile. You should use Grid for that.
Screenshot 2019-12-13 at 08 10 40

The values are not visible in the popup. I suspect that that should be the count of the elements in the state.
Screenshot 2019-12-13 at 08 11 09

**Comment by cjdcordeiro** [comment]
cannot reproduce the issue. we'll have a look together on monday

**Comment by 0xbase12** [comment]
This issue is reported here and we are using the last version which is 2.9.3 https://github.com/chartjs/Chart.js/issues/6188

**Comment by cjdcordeiro** [comment]
@0xbase12 lgtm. just renamed something. If the builds pass you can merge

**Pull request merged**
